SymfonyProject/agenceimmo/src/Entity/Bien.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BienRepository")
 */
class Bien
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type", inversedBy="famille")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Famille")
     * @ORM\JoinColumn(nullable=false)
     */
    private $famille;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isExclusif;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="integer")
     */
    private $piece;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean", options={"default":true})
     */
    private $isVisible;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Lieu", inversedBy="biens")
     * @ORM\JoinColumn(nullable=false)
     */
    private $lieu;

    public function __construct()
    {
        $this->reference = substr(md5(rand()), 1, 6);
        $this->isVisible = true;
        $this->createdAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getFamille(): ?Famille
    {
        return $this->famille;
    }

    public function setFamille(?Famille $famille): self
    {
        $this->famille = $famille;

        return $this;
    }

    public function getIsExclusif(): ?bool
    {
        return $this->isExclusif;
    }

    public function setIsExclusif(bool $isExclusif): self
    {
        $this->isExclusif = $isExclusif;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getPiece(): ?int
    {
        return $this->piece;
    }

    public function setPiece(int $piece): self
    {
        $this->piece = $piece;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getFormatedPrix(): string
    {
        return number_format($this->prix, 0, '', ' ');
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsVisible(): ?bool
    {
        return $this->isVisible;
    }

    public function setIsVisible(bool $isVisible): self
    {
        $this->isVisible = $isVisible;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }


}

SymfonyProject/agenceimmo/src/Controller/AgenceController.php
<?php

namespace App\Controller;

use App\Entity\Bien;
use App\Form\BienType;
use App\Entity\Contact;
use App\Entity\Famille;
use App\Form\ContactType;
use App\Notification\ContactNotification;
use App\Repository\BienRepository;
use App\Repository\FamilleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AgenceController extends AbstractController
{

    /**
     * @Route("/", name="home")
     */
    public function home(BienRepository $repo)
    {
        $biens = $repo->findBy(['type'=>true], ['createdAt' => 'DESC'], 12);

        return $this->render('agence/home.html.twig', [
            'controller_name' => 'AgenceController',
            'biens' => $biens
        ]);
    }

    /**
     * @Route("/ventes", name="ventes_show")
     */
    public function ventes_show(BienRepository $repo)
    {

        $biens_type = $repo->findBy(['isVisible'=>true, 'type'=>1], ['createdAt' => 'DESC']);

        return $this->render('agence/full_show.html.twig', [
            'controller_name' => 'AgenceController',
            'biens_type' => $biens_type

        ]);
    }

    /**
     * @Route("/locations", name="locations_show")
     */
    public function locations_show(BienRepository $repo)
    {
        $biens_type = $repo->findBy(['isVisible'=>true, 'type'=>2], ['createdAt' => 'DESC']);
        return $this->render('agence/full_show.html.twig', [
            'controller_name' => 'AgenceController',
            'biens_type' => $biens_type

        ]);
    }

    /**
     * @Route("/show/{reference}", name="bien_show")
     */
    public function show(Bien $bien, $reference)
    {
        return $this->render('agence/show.html.twig', [
            'controller_name' => 'AgenceController',
            'bien' => $bien
        ]);
    }

    /**
     * @Route("/bien/new",name = "bien_create")
     * @Route("/bien/{reference}/edit",name = "bien_edit")
     *
     * @param Bien $bien
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return void
     */
    public function form(Bien $bien = null, Request $request, EntityManagerInterface $em){

        if (!$bien){
            $bien = new Bien();
        }
        $form = $this->createForm(BienType::class, $bien);

        $form->handleRequest($request);

        if($form->isSubmitted()&&$form->isValid()){
            $em->persist($bien);
            $em->flush();
            return $this->redirectToRoute('bien_show', ['reference' => $bien->getReference()]);
        }
        return $this->render('agence/create.html.twig', [
            'formBien' => $form->createView(),
            'editMode' => $bien->getReference()!==null
        ]);

    }

    /**
     * @Route("/services", name="services")
     */
    public function services()
    {
        return $this->render('agence/services.html.twig', [
            'controller_name' => 'AgenceController',
        ]);
    }

    /**
     * @Route("/contact", name="contact")
     */
    public function contact(Request $request, ContactNotification $notifiaction)
    {
        $contact = new Contact();
        $form = $this->createForm(ContactType::class, $contact);

        $form->handleRequest($request);

        if($form->isSubmitted()&&$form->isValid()){
            $notifiaction->notify($contact);
            $this->addFlash('success', 'Votre email à bien été envoyé');
            return $this->redirectToRoute('contact');
        }

        return $this->render('agence/contact.html.twig', [
            'controller_name' => 'AgenceController',
            'formContact' => $form->createView()
        ]);
    }
  
}

SymfonyProject/agenceimmo/templates/agence/contact.html.twig
{% extends 'base.html.twig' %}

{% block body %}

</br>
<h1>Contact</h1>
</br></br>
<div class="row">

<div class="col-2 .col-sm-6" >



<h4><strong>Agence appéré</strong></h4>
</br>
<p>28 rue de Monge</br>
29200, Brest</p>



</div>

    <div class="col-sm">



<div id="map" ></div></div>
    <div class="col-sm">
{{ form_start(formContact)}}
{{form_row(formContact.firsname, {'attr': {'placeholder':"Prénom"}})}}
{{form_row(formContact.lastname, {'attr': {'placeholder':"Nom"}})}}
{{form_row(formContact.phone, {'attr': {'placeholder':"Numéro de téléphone"}})}}
{{form_row(formContact.email, {'attr': {'placeholder':"email"}})}}
{{form_row(formContact.message, {'attr': {'placeholder':"message"}})}}
{% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
<button type="submit" class="btn btn-primary">Envoyer le message</button>
{{ form_end(formContact)}}</col-sm>
</div>

</div>


    <script>

      function initMap() {
        var myLatLng = {lat: 48.38435, lng: -4.491963};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 17,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDQiUtXg6uBCaJ8pH0aJbn7szhdUBSYMSA&callback=initMap">
    </script>
{% endblock %}

SymfonyProject/agenceimmo/templates/agence/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{% if editMode %}
<h1>Edition du bien</h1>
{% else %}
<h1>Création du bien </h1>
{% endif %} 

{{ form_start(formBien)}}
{{form_row(formBien.titre, {'attr': {'placeholder':"Titre du bien"}})}}

<button type="submit" class="btn btn-primary">
{% if editMode %}
<h1>Enregistrer les modifications</h1>
{% else %}
<h1>Ajouter le bien</h1>
{% endif %} 
</button>
{{ form_end(formBien)}}



{% endblock %}

SymfonyProject/agenceimmo/templates/agence/full_show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>Annonces de </h1>
{% for bien in biens_type %}
    <a href="{{path('bien_show', {'reference': bien.reference})}}">
        <h2>{{bien.titre}}</h2>
        <div class="metadata">
        {{bien.prix}} {{bien.type.label}}
        </div>
        <div>
        {{bien.description}}
        </div>
    </a>
{% endfor %}{% endblock %}

SymfonyProject/agenceimmo/templates/agence/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>Dernieres annonces !</h1>
{% for bien in biens %}
    <a href="{{path('bien_show', {'reference': bien.reference})}}">
        <h2>{{bien.titre}}</h2>
        <div class="metadata">
        {{bien.formatedPrix}} € {{bien.type.label}}
        </div>
        <div>
        {{bien.description}}
        </div>
    </a>
{% endfor %}

{% endblock %}

SymfonyProject/agenceimmo/templates/agence/services.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>Service</h1>
{% endblock %}

SymfonyProject/agenceimmo/templates/agence/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <bien>
        <h2>{{bien.titre}}</h2>
        <div class="metadata">
        {{bien.prix}} {{bien.type.label}}
        </div>
        <div>
        {{bien.description}}
        </div>
    </bien>
{% endblock %}